apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: finrem-cos
  namespace: financial-remedy
spec:
  values:
    java:
      environment:
        IDAM_API_URL: https://idam-api.platform.hmcts.net
        IDAM_API_REDIRECT_URL: https://www.financial-remedy.reform.hmcts.net/oauth2/callback
        CTSC_EMAIL: contactFinancialRemedy@justice.gov.uk
        ASSIGNED_TO_JUDGE_DEFAULT_EMAIL: newApplication@justice.gov.uk
        PAYMENT_API_URL: "http://payment-api-prod.service.core-compute-prod.internal"
        FEES_API_URL: "http://fees-register-api-prod.service.core-compute-prod.internal"
        FEATURE_PBA_CASE_TYPE: false
        FEATURE_USE_USER_TOKEN: true
        FEATURE_SOLICITOR_NOC: true
        FEATURE_CASEWORKER_NOC: true
        VAR_FLUX_V2: trigger3
