apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pcq-consolidation-service
spec:
  values:
    job:
      suspend: true
      schedule: "0 18 2-30/2 * *"
      environment:
        IDAM_API_URL: https://idam-api.platform.hmcts.net
