apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: em-anno
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/em/anno:prod-db867e2-20220926175629 #{"$imagepolicy": "flux-system:demo-em-anno"}
      environment:
        TEST_VAR: value1
