apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rd-location-ref-data-load
spec:
  values:
    job:
      schedule: "00 16 * * *"
      useInterpodAntiAffinity: true
      image: hmctspublic.azurecr.io/rd/location-ref-data-load:pr-240-e69ef9b-20220222145105
      environment:
        DELETE_ORG: false
      keyVaults:
        "rd":
          resourceGroup: rd
          secrets:
            - name: location-ref-api-POSTGRES-PASS
              alias: spring.datasource.password
            - ApplicationInsightsInstrumentationKey
            - name: rd-location-storage-account-name
              alias: ACCOUNT_NAME
            - name: rd-location-storage-account-primary-key
              alias: ACCOUNT_KEY
            - name: CONTAINER-NAME
              alias: CONTAINER_NAME
