apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rd-location-ref-data-load
spec:
  values:
    job:
      suspend: true
      schedule: "30 16 * * *"
      environment:
        DELETE_ORG: false
