apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: refund-approved-update-process
  namespace: fees-pay
spec:
  releaseName: refund-approved-update-process
  rollback:
    enable: true
    retry: true
  chart:
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    name: payment-jobs
    version: 0.0.11
  values:
    job:
      image: "hmctspublic.azurecr.io/payment/jobs:pr-30-65581b2-20211117164106"   #{"$imagepolicy": "flux-system:refund-approved-update-process"}
      schedule: "*/30 * * * *"
      environment:
        REPORT_NAME: refund-approved-update-process
        DUMMY_RESTART_VAR: false
    global:
      environment: demo
      tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      enableKeyVaults: true
      jobKind: CronJob
