apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmc-citizen-frontend
spec:
  releaseName: cmc-citizen-frontend
  values:
    nodejs:
      image: hmctspublic.azurecr.io/cmc/citizen-frontend:latest #{"$imagepolicy": "citizen-frontend:latest"}
  chart:
    spec:
      chart: ./stable/cmc-citizen-frontend
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
