apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: em-stitching
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/em/stitching:prod-ce25e5b-20220926175753 #{"$imagepolicy": "flux-system:demo-em-stitching"}
      environment:
        TEST_VAR: value1
