apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: wa-case-event-handler
spec:
  values:
    java:
      environment:
        AZURE_SERVICE_BUS_FEATURE_TOGGLE: true
        AZURE_SERVICE_BUS_DLQ_FEATURE_TOGGLE: true
        LOGGING_LEVEL_UK_GOV_HMCTS: DEBUG
        RESTART: true
        PROBLEM_MESSAGE_RESET_ID_LIST: ID:e48a55c9-36a5-4543-a4bb-0c3def3f67f9:18:1:1-105,ID:c955225a-164c-47d2-886c-37b801ac7840:3:1:1-2