---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-config
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 3m0s
  ref:
    branch: prod-freeze
  secretRef:
    name: git-credentials
  url: ssh://git@github.com/hmcts/cnp-flux-config