apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docmosis
spec:
  values:
    ingressHost: docmosis.ithc.platform.hmcts.net
    image: hmctsprivate.azurecr.io/docmosis:ithc-c053030-220484 #{"$imagepolicy": "flux-system:ithc-docmosis"}
