apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: status-payment-job
  namespace: fees-pay
spec:
  releaseName: status-payment-job
  values:
    job:
      suspend: true
      environment:
        REPORT_NAME: status-update
    global:
      environment: prod
