apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: em-npa
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/em/npa:prod-02db381-20220926175702 #{"$imagepolicy": "flux-system:demo-em-npa"}
      environment:
        TEST_VAR: value1
