apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dead-letter-queue-process
spec:
  values:
    job:
      suspend: true
      environment:
        DUMMY_RESTART_VAR: true
    global:
      environment: prod
