apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: docmosis
spec:
  values:
    ingressHost: docmosis.aat.platform.hmcts.net
    image: hmctsprivate.azurecr.io/docmosis:aat-aeea2b3-274828 #{"$imagepolicy": "flux-system:aat-docmosis"}
