apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: docmosis
spec:
  values:
    ingressClass: traefik-private
    ingressHost: docmosis.demo.platform.hmcts.net
    disableTraefikTls: false
    image: hmctsprivate.azurecr.io/docmosis:demo-aeea2b3-274828 #{"$imagepolicy": "flux-system:demo-docmosis"}
