apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: et-sya-api
spec:
  releaseName: et-sya-api
  values:
    java:
      replicas: 2
      useInterpodAntiAffinity: true
      image: hmctspublic.azurecr.io/et/sya-api:prod-554d11a-20220926112037 #{"$imagepolicy": "flux-system:et-sya-api"}
  chart:
    spec:
      chart: ./stable/et-sya-api
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
