apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ccpay-paymentoutcome-web
spec:
  values:
    nodejs:
      replicas: 2
      useInterpodAntiAffinity: true
      image: hmctspublic.azurecr.io/ccpay/paymentoutcome-web:pr-8-54a245e-20211117131251   #{"$imagepolicy": "flux-system:demo-ccpay-paymentoutcome-web"}
      imagePullPolicy: Always
      environment:
        DUMMY_VARIABLE: false
