apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dg-docassembly
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/dg/docassembly:prod-39f8fbd-20220926175726 #{"$imagepolicy": "flux-system:demo-dg-docassembly"}
      environment:
        TEST_VAR: value1
